# Generated by Django 5.2.8 on 2025-11-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='author_photos/')),
                ('Nationality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=100, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('last_read_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Edition', models.CharField(blank=True, max_length=100, null=True)),
                ('NumberOfPages', models.PositiveIntegerField()),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Language', models.CharField(blank=True, max_length=50, null=True)),
                ('PublishDate', models.DateField(blank=True, null=True)),
                ('ebook_content_url', models.FileField(blank=True, null=True, upload_to='ebooks/')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
                ('categories', models.ManyToManyField(related_name='books', to='books.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book')),
            ],
        ),
    ]
